### ISSUE TITLE
Using your code with MacOS app

### ISSUE THREAD

**Issue by CryptoAngel** [mountaineerbr/markets#1]
Hello,

Is it possible to use this code on MacOS app with result graphic display?

Regards

**Comment by mountaineerbr** [comment]
Hello Crypto Angel.
Uhmmm... I am not sure, probably these scripts may not work under MacOS X without some modifications.. I did not understand what you mean by code on MacOS app with result graphic display, sorry... Thanks for the question! Cheers!

**Comment by CryptoAngel** [comment]
Thank you for your quick reply.
I want to program MacOS app that can bull info from WhalreAlert using API and display the result and/or graphs on a form.
Also to able set alerts to be fired on screen or/and send emails.
What do you think?

**Comment by mountaineerbr** [comment]
Hey, that is a good idea. My script which uses the WhaleAlert api is one of the most visited in my repo, people really seem to like WhaleAlert. If you manage to get an API key from WhaleAlert, then I think you will have a good app. The problem is their free API limits are very small, for example you cannot get data older than one hour and request number per day is small, too. Good luck!

**Comment by CryptoAngel** [comment]
Thank you.
I have paid account so no problem with the API.
For using your code, I think the best would be convert it to xcode / SWIFT so it will run natively. Do you know how and be able to help?
Regards

**Comment by mountaineerbr** [comment]
I did not put much effort into that whalealert.sh script as i was very disappointed about the strict limits (only saw them carefully later!).. and i plan to update it no more, either..
their api documentation is good, i don't think you will find much problem in implementing those api calls but how your users will use those functions.. i do not know any language other shell scripting, lol.. good luck!

**Comment by CryptoAngel** [comment]
Hi again ;-)

Running your WhalreAlert script result with errors:
whalealert.sh: line 184: jq: command not found
whalealert.sh: line 189: jq: command not found

Any idea?

Also, which currency it's looking for? Like currency=BTC
for example, I use this to get the result I am looking for:
GET https://api.whale-alert.io/v1/transactions?api_key=XxXxXxXxXxXxXxXxXxXx&min_value=10000000&start=1592524800&cursor=2ca210e1-2ca210e1-5eedc317&currency=BTC

Last thing, the above return also the last cursor position which I want to keep and use it for the next call so I will get the latest result without scanning transaction that already scanned, do you know how can I keep the last curser and then use it for the next call?

THANK YOU SO MUCH ;-D

**Comment by mountaineerbr** [comment]
hey cryptoangel!

jq is a widely available json parser found in linux repositories, because i don't parse json with awk or sed, that would be too painful.

about what currency it is looking for.. i think the defaults is against the US dollar.  i cannot remember the api details anymore, it has been many months already..

well, if you really want to keep the cursor between runs of the programme, i would suggest it creates a file with the cursor key and keep it in the programme configuration directory or cache directory... That is what i would do with shell scripts. When it starts again, check for the cursor file and if so, read it, otherwise start from the beggining...
